Added test for the personRepository using mockito and adding necessery  dependency to pom.xml part of #10
Win-ther/JakartaEELab1 pull request #25
Opened 2024-03-02 13:08 UTC by Charlottehenriksson

Added test for the personRepository using mockito and adding necessary dependency to pom.xml
Including only tests for PersonRepository and added dependency to pom.xml

2024-03-02 16:25 UTC, Danback commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        doNothing().when(entityManager).persist(any());
Is this line needed? persist here should do nothing by default when it's mocked.
I could be wrong though.

@Test
void createPersonTest() {
    Person person = new Person();

    personRepository.createPerson(person);

    verify(entityManager).persist(person); 
}

2024-03-02 16:48 UTC, Win-ther requested changes
The tests give full coverage and seems to test that the methods have been called correctly.
There is some changes I would like to see though.

2024-03-02 16:55 UTC, Win-ther requested changes

2024-03-02 16:55 UTC, Win-ther commented on pom.xml
> +        </dependency>
Mockito Version 5.11.0 seems to be out as of 1/3-2024, maybe we should update it to the latest?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        doNothing().when(entityManager).persist(any());
The test seems to be working even without thelling persist to do nothing, is this part neccesary?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        jakarta.persistence.TypedQuery<Person> typedQueryMock = mock(jakarta.persistence.TypedQuery.class);
This is weird, why have you chosen to not just import jakarta.persistence.TypedQuery?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        when(entityManager.find(eq(Person.class), eq(id))).thenReturn(person);
The eq()-method calls seems unnecessary, it works fine when passing the values directly. SonarLint even comments on it, why have you chosen to use eq() here?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        when(entityManager.find(eq(Person.class), eq(id))).thenReturn(person);
The eq()-method calls seems unnecessary, it works fine when passing the values directly. SonarLint even comments on it, why have you chosen to use eq() here?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        assertEquals(updatedPerson, result);
This assert seems unnecessary aswell, if result is equals to updatedPerson. Is it not by default not null?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        assertEquals(person, result);
This assert seems unnecessary aswell, if result is equals to person. Is it not by default not null?

2024-03-02 16:55 UTC, Win-ther commented on src/test/java/se/iths/jakartaeelab1/repository/PersonRepositoryTest.java
> +        assertEquals(personList, result);
This assert seems unnecessary aswell, if result is equals to personList. Is it not by default not null?

2024-03-06 21:18 UTC, Win-ther commented
You have some conflicts in your pom.xml still

2024-03-07 08:19 UTC, altmannk approved these changes
LGTM 👍🏽

2024-03-07 09:05 UTC, Win-ther approved these changes
Tests looks good now and gives full coverage for the PersonRepository-class. Good job! :)

2024-03-07 09:05 UTC, merged